<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net8.0-windows</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Version>1.0.2</Version>
	</PropertyGroup>
	<ItemGroup>
		<None Remove="Assets\icon.png" />
		<None Remove="Assets\preview.png" />
		<None Remove="ExpressionTreeControl.xaml" />
		<None Remove="LICENSE.txt" />
	</ItemGroup>
	<ItemGroup>
		<EmbeddedResource Include="ExpressionTreeControl.xaml">
			<Generator>MSBuild:Compile</Generator>
		</EmbeddedResource>
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.VisualStudio.Extensibility.Sdk" Version="17.9.2092" />
		<PackageReference Include="Microsoft.VisualStudio.Extensibility.Build" Version="17.9.2092" />
	</ItemGroup>

	<ItemGroup>
	  <Content Include="..\ExpressionTreeExplorer.ObjectSource\bin\$(Configuration)\netstandard2.0\ExpressionTreeExplorer.ObjectSource.dll">
		<Link>netstandard2.0\ExpressionTreeExplorer.ObjectSource.dll</Link>
		<IncludeInVSIX>true</IncludeInVSIX>
		<CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Content>
	</ItemGroup>

	<ItemGroup>
	  <Content Include="..\ExpressionTreeExplorer.Core\bin\$(Configuration)\netstandard2.0\ExpressionTreeExplorer.Core.dll">
		<Link>netstandard2.0\ExpressionTreeExplorer.Core.dll</Link>
		<IncludeInVSIX>true</IncludeInVSIX>
		<CopyToOutputDirectory>Never</CopyToOutputDirectory>
	  </Content>
	  <Content Include="Assets\icon.png" />
	  <Content Include="Assets\preview.png" />
	  <Content Include="LICENSE.txt" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\ExpressionTreeExplorer.Core\ExpressionTreeExplorer.Core.csproj" />
		<ProjectReference Include="..\ExpressionTreeExplorer.ObjectSource\ExpressionTreeExplorer.ObjectSource.csproj" />
	</ItemGroup>
</Project>
